### PR TITLE
Added support for NodeMCU (WiFI).

### PR DESCRIPTION
**Pull request by ProximaB**
I added and tested  support for NodeMCU, it's microcontroller based on ESP8266.
I also reorganize the project and migrate to Visual Micro, beacuse it's awesome.
Every examples will be added to the project as independent project soon.
I am enclosing a screenshot for people who do not know what VIsual MIcro is. 
I hope you'll like it. 🤟
image

### CODE REVIEW

**Comment by ildemartinez** [comment]
Hello!!!

great job!!! have you tested it with Arduino so both versions work great together? to merge pull ;)

all the best
ilde

**Comment by ProximaB** [comment]
Sorry it's taken me so long to write. Thanks you for the greeting.
I tested it with ESP-12E and ESP-01S, and it worked. Of course its still compatible with serial and ethernet like before.
I will make another pull request with code that is compatible with your repo and continue this the way i described above.
Could I ask you about Arduino OPC Server? Is it code available? Is it possible to write this server without any licence etc.? I want to do something like that free, but opcfoundation.org servers are down and I can't get any information about it.
Best regards
Bartek

**Comment by ildemartinez** [comment]
Dear Bartek

Thank you for your great work!! 

OPC for Arduino OPC Server is Delphi programed and I would like to release the sources for free and open but it need to be a bit clean up ;)

Are you interested on it? I think not too much people use Delphi but it is my loved programming languaje

all the best
ilde

**Comment by ProximaB** [comment]
It would be great move to make it open. Unfortunelly i don't know pascal, but it looks good and i think you should stick to it if you like it. This month I am very busy, and can not contribute, sorry for delay.
So, I'm really looking forward to see OPC server in your repository. 😊  
Best regards
Bartek

**Pull request merged**
